# Generated by Django 3.1.2 on 2020-11-02 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
