# Generated by Django 3.1.2 on 2020-11-02 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('bancos', '0001_initial'),
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temporadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=200, verbose_name='Subtitulo')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('ap_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('genero', models.IntegerField(verbose_name='Genero')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('razon_social', models.CharField(max_length=100, unique=True, verbose_name='Razon social')),
                ('nombre_marca', models.CharField(max_length=50, verbose_name='Nombre de Marca')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('no_ext', models.CharField(max_length=6, verbose_name='N° Exterior')),
                ('no_int', models.CharField(max_length=6, verbose_name='N° Interior')),
                ('cp', models.IntegerField()),
                ('direccion_comercial', models.BooleanField(default=True, verbose_name='Dirección comercial')),
                ('com_calle', models.CharField(max_length=200, verbose_name='Comercial calle')),
                ('com_no_ext', models.CharField(max_length=6, verbose_name='Comercial N° exterior')),
                ('com_cp', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
                ('hecho_mexicano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hecho_mexicano', to='imagenes.documentos')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identificación', to='imagenes.documentos')),
                ('info_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bancos.infobancos')),
                ('razon_social_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razon_social_doc', to='imagenes.documentos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Costo')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Descuento')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuarios')),
                ('es_para', models.ManyToManyField(to='productos.Generos')),
                ('imagen', models.ManyToManyField(to='imagenes.Imagenes')),
                ('proveedor', models.ManyToManyField(to='productos.Proveedores')),
                ('temporada', models.ManyToManyField(to='productos.Temporadas')),
                ('tipo_producto', models.ManyToManyField(to='productos.TipoProductos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
