# Generated by Django 3.1.2 on 2020-11-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=40)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('genero', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
